version: '3.7'

services:
  db:
    image: mysql:8.0
    container_name: fast-food-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    env_file:
      - .env
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 3s
      retries: 10
    ports:
      - "3306:3306"
    volumes:
      - .docker/dbdata/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_HOST: "test"
