apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-food-deployment
  labels:
    app: fast-food
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fast-food
  template:
    metadata:
      labels:
        app: fast-food
    spec:
      securityContext:
        {}
      containers:
        - name: fast-food
          image: tshadz/fast-food-app:1.0.1
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: fast-food-config
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /swagger
          #     port: 8080
          # readinessProbe:
          #   httpGet:
          #     path: /swagger
          #     port: 8080
          resources:
            null