apiVersion: v1
kind: Service
metadata:
  name: fast-food-svc
  labels:
    app: fast-food
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
      protocol: TCP
      name: http
  selector:
    app: fast-food