apiVersion: v1
kind: Secret
metadata:
  name: fast-food-db-secret
type: Opaque
stringData:
  MYSQL_HOST: "fast-food-db"
  MYSQL_ROOT_PASSWORD: "root"
  MYSQL_DATABASE: "fastfood"
  MYSQL_ROOT_USER: "root"
  MYSQL_USER: "user"
  MYSQL_PASSWORD: "user"

