apiVersion: v1
kind: Service
metadata:
  name: fast-food-db
  namespace: default
  labels:
    app: fast-food-db
spec:
  selector:
    app: fast-food-db
  ports:
  - name: fast-food-db
    protocol: TCP
    port: 3306
    targetPort: 3306