name: Pipeline Workflow

on:
  push:
    branches: [ "k8s" ]
  pull_request:
    branches: [ "k8s" ]
  workflow_dispatch:

jobs:
  call-workflow-branch-ref:
    uses: tshadz-fiap-postech-soat3/ci-pipeline/.github/workflows/ci-pipeline.yml@main
    secrets: inherit
